"""Bazel build file for libvpx."""

load("@bazel_skylib//lib:selects.bzl", "selects")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_license//rules:license.bzl", "license")
load("@rules_nasm//nasm:defs.bzl", "nasm_cc_library")
load("//bazel:defs.bzl", "generate_tests")
load(
    "//bazel:libvpx_srcs.bzl",
    "libvpx_arm64_c_srcs",
    "libvpx_x86_64_asm_srcs",
    "libvpx_x86_64_c_srcs",
)

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        "@rules_license//licenses/spdx:BSD-3-Clause",
    ],
    visibility = [":__subpackages__"],
)

exports_files(["libvpx/test/test-data.sha1"])

config_setting(
    name = "linux_aarch64",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "linux_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "osx_apple",
    constraint_values = [
        "@platforms//os:osx",
        "@platforms//cpu:aarch64",
    ],
)

config_setting(
    name = "osx_intel",
    constraint_values = [
        "@platforms//os:osx",
        "@platforms//cpu:x86_64",
    ],
)

config_setting(
    name = "windows_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
    ],
)

selects.config_setting_group(
    name = "aarch64",
    match_any = [
        ":linux_aarch64",
        ":osx_apple",
    ],
)

selects.config_setting_group(
    name = "x86_64",
    match_any = [
        ":linux_x86_64",
        ":windows_x86_64",
        ":osx_intel",
    ],
)

DEFAULT_COPTS = [
    "-U_FORTIFY_SOURCE",
    "-D_FORTIFY_SOURCE=0",
    "-D_LARGEFILE_SOURCE",
    "-D_FILE_OFFSET_BITS=64",
    "-Wall",
    "-Wno-conversion",
    "-Wno-parentheses-equality",
    "-Wno-unused-function",
    "-Wdisabled-optimization",
    "-Wfloat-conversion",
    "-Wformat=2",
    "-Wpointer-arith",
    "-Wtype-limits",
    "-Wcast-qual",
    "-Wvla",
    "-Wimplicit-function-declaration",
    "-Wmissing-declarations",
    "-Wmissing-prototypes",
    "-Wshadow",
    "-Wno-strict-prototypes",
    "-Wuninitialized",
    "-Wunused",
    "-Wextra",
    "-Wundef",
]

INCLUDE_CFG = ["config"] + select({
    ":linux_x86_64": ["config/x86_64"],
    ":windows_x86_64": ["config/x86_64"],
    ":osx_apple": ["config/arm64"],
})

HDRS_CFG = select({
    ":linux_x86_64": [
        "config/x86_64/vp8_rtcd.h",
        "config/x86_64/vp9_rtcd.h",
        "config/x86_64/vpx_config.h",
        "config/x86_64/vpx_dsp_rtcd.h",
        "config/x86_64/vpx_config.asm",
        "config/x86_64/vpx_scale_rtcd.h",
        "config/x86_64/vpx_version.h",
    ],
    ":windows_x86_64": [
        "config/x86_64/vp8_rtcd.h",
        "config/x86_64/vp9_rtcd.h",
        "config/x86_64/vpx_config.h",
        "config/x86_64/vpx_config.asm",
        "config/x86_64/vpx_dsp_rtcd.h",
        "config/x86_64/vpx_scale_rtcd.h",
        "config/x86_64/vpx_version.h",
    ],
    ":osx_apple": [
        "config/arm64/vpx_config.h",
        "config/arm64/vpx_version.h",
        "config/arm64/vp8_rtcd.h",
        "config/arm64/vp9_rtcd.h",
        "config/arm64/vpx_dsp_rtcd.h",
        "config/arm64/vpx_scale_rtcd.h",
    ],
})

ASM_HDRS_CFG = select({
    ":linux_x86_64": [
        "config/x86_64/vpx_config.asm",
    ],
    ":windows_x86_64": [
        "config/x86_64/vpx_config.asm",
    ],
    ":osx_apple": [],
})

nasm_cc_library(
    name = "libvpx_asm",
    srcs = libvpx_x86_64_asm_srcs,
    hdrs = [
        "libvpx/third_party/x86inc/x86inc.asm",
        "libvpx/vpx_dsp/x86/bitdepth_conversion_sse2.asm",
        "libvpx/vpx_ports/x86_abi_support.asm",
    ] + ASM_HDRS_CFG,
    copts = select({
        "@platforms//os:windows": ["-fwin64"],
        "@platforms//os:linux": [
            "-felf64",
            "-DWEB_X86_64",
        ],
        "@platforms//os:macos": ["-fmacho64"],
    }),
    includes = INCLUDE_CFG + ["libvpx"],
    linkstatic = True,
)

# Note that this is a libvpx encoder configured for realtime encoding.
# This is likely not what you want to use for multipass encoders
# such as used in ffmpeg.
cc_library(
    name = "libvpx",
    srcs = select({
        ":x86_64": libvpx_x86_64_c_srcs,
        ":osx_apple": libvpx_arm64_c_srcs,
        "//conditions:default": [],
    }) + glob(["libvpx/**/*.h"]),
    hdrs = HDRS_CFG,
    copts = DEFAULT_COPTS + select({
        ":x86_64": [
            "-mmmx",
            "-mavx2",
        ],
        ":osx_apple": [],
        "//conditions:default": [],
    }),
    includes = INCLUDE_CFG + ["libvpx"],
    linkopts = [
        "-lpthread",
        "-lrt",
    ],
    linkstatic = 1,
    deps = ["@libyuv"] +
           select({
               ":x86_64": [":libvpx_asm"],
               "//conditions:default": [],
           }),
)

TESTS = [
    "libvpx/third_party/googletest/src/src/gtest-death-test.cc",
    "libvpx/third_party/googletest/src/src/gtest.cc",
    "libvpx/third_party/googletest/src/src/gtest-typed-test.cc",
    "libvpx/test/vp8_fdct4x4_test.cc",
    "libvpx/test/comp_avg_pred_test.cc",
    "libvpx/test/vpx_scale_test.cc",
    "libvpx/test/aq_segment_test.cc",
    "libvpx/test/quantize_test.cc",
    "libvpx/test/encode_api_test.cc",
    # "libvpx/test/vp8_denoiser_sse2_test.cc", # X86 only
    "libvpx/test/dct32x32_test.cc",
    "libvpx/test/y4m_test.cc",
    "libvpx/test/cpu_speed_test.cc",
    "libvpx/test/vp8_decrypt_test.cc",
    "libvpx/test/vp9_scale_test.cc",
    "libvpx/test/vp9_decrypt_test.cc",
    "libvpx/test/vp9_ethread_test.cc",
    "libvpx/test/dct16x16_test.cc",
    "libvpx/test/dct_partial_test.cc",
    "libvpx/test/vp9_motion_vector_test.cc",
    "libvpx/test/sad_test.cc",
    "libvpx/test/minmax_test.cc",
    "libvpx/test/lpf_test.cc",
    "libvpx/test/vp9_boolcoder_test.cc",
    "libvpx/test/tile_independence_test.cc",
    "libvpx/test/error_resilience_test.cc",
    "libvpx/test/resize_test.cc",
    "libvpx/test/vp9_subtract_test.cc",
    "libvpx/test/datarate_test.cc",
    "libvpx/test/vp8_boolcoder_test.cc",
    "libvpx/test/vp9_block_error_test.cc",
    "libvpx/test/keyframe_test.cc",
    "libvpx/test/idct_test.cc",
    "libvpx/test/predict_test.cc",
    "libvpx/test/variance_test.cc",
    "libvpx/test/superframe_test.cc",
    "libvpx/test/avg_test.cc",
    "libvpx/test/altref_test.cc",
    "libvpx/test/cq_test.cc",
    "libvpx/test/vp9_intrapred_test.cc",
    "libvpx/test/borders_test.cc",
    "libvpx/test/vp9_quantize_test.cc",
    "libvpx/test/partial_idct_test.cc",
    "libvpx/test/vp9_lossless_test.cc",
    "libvpx/test/dct_test.cc",
    "libvpx/test/config_test.cc",
    "libvpx/test/alt_ref_aq_segment_test.cc",
    "libvpx/test/active_map_refresh_test.cc",
    # "libvpx/test/pp_filter_test.cc",
    "libvpx/test/sum_squares_test.cc",
    "libvpx/test/vp8_fragments_test.cc",
    "libvpx/test/idct8x8_test.cc",
    "libvpx/test/fdct8x8_test.cc",
    "libvpx/test/vp9_end_to_end_test.cc",
    "libvpx/test/vp9_arf_freq_test.cc",
    "libvpx/test/decode_api_test.cc",
    "libvpx/test/realtime_test.cc",
    "libvpx/test/convolve_test.cc",
    # "libvpx/test/add_noise_test.cc", X86 only..
    "libvpx/test/hadamard_test.cc",
    "libvpx/test/active_map_test.cc",
    "libvpx/test/level_test.cc",
    # "libvpx/test/test_vector_test.cc",
]

cc_library(
    name = "libvpx_test_tools",
    srcs = [
        "libvpx/ivfenc.c",
        "libvpx/md5_utils.c",
        "libvpx/test/decode_test_driver.cc",
        "libvpx/test/encode_test_driver.cc",
        "libvpx/test/set_roi.cc",

        # We use a custom gmain that will inject the LIBVPX_TEST_DATA_PATH environment
        # variable that will point to the bazel runfiles directory where all the
        # test data can be found.
        "libvpx/test/emu_dev_gmain.cc",
        "libvpx/test/test_vectors.cc",
        "libvpx/test/vp9_encoder_parms_get_to_decoder.cc",
        "libvpx/y4menc.c",
        "libvpx/y4minput.c",
        "libvpx/third_party/googletest/src/src/gtest.cc",
        "libvpx/third_party/googletest/src/src/gtest-death-test.cc",
        "libvpx/third_party/googletest/src/src/gtest-port.cc",
        "libvpx/third_party/googletest/src/src/gtest-filepath.cc",
        "libvpx/third_party/googletest/src/src/gtest-test-part.cc",
        "libvpx/third_party/googletest/src/src/gtest-printers.cc",
    ] + glob([
        "libvpx/**/*.h",
        "libvpx/third_party/googletest/src/**/*.h",
    ]),
    hdrs = [
        "libvpx/ivfenc.h",
        "libvpx/md5_utils.h",
        "libvpx/test/test_libvpx.cc",
        "libvpx/third_party/googletest/src/src/gtest.cc",
        "libvpx/third_party/googletest/src/src/gtest-death-test.cc",
        "libvpx/third_party/googletest/src/src/gtest-filepath.cc",
        "libvpx/third_party/googletest/src/src/gtest-port.cc",
        "libvpx/third_party/googletest/src/src/gtest-printers.cc",
        "libvpx/third_party/googletest/src/src/gtest-test-part.cc",
        "libvpx/third_party/googletest/src/src/gtest-typed-test.cc",
        "libvpx/tools_common.h",
        "libvpx/webmdec.cc",
        "libvpx/y4menc.h",
        "libvpx/y4minput.h",
    ] + glob(["libvpx/test/*.h"]),
    data = ["@libvpx_test_vectors//:vectors"],
    includes = [
        "libvpx/third_party/googletest/src",
        "libvpx/third_party/googletest/src/include",
    ],
    linkopts = [
        "-lpthread",
        "-lrt",
    ],
    deps = [
        ":libvpx",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

# Note! These tests are extremely slow and will fetch all the dependencies
# (video files)
# what is worse is that the configuration files have configured the encoder
# to be "realtime", which results in various test failures related
# to g_lag_in_frames out of range [..0] and multi pass encoding not existing.
# The tests appear to "assume" that this will be always available, so
# Best use case for these right now is to validate that build works.
generate_tests(
    name = "vpx_suite",
    tests = TESTS,
)
