module(
    name = "libvpx",
    version = "1.7.0",
)

bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "libvpx_test_data", version = "0.0.1")
bazel_dep(name = "libyuv", version = "0.0.1")
bazel_dep(name = "nasm", version = "2.16.03.bcr.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_nasm", version = "0.4.0")
bazel_dep(name = "rules_python", version = "1.8.2")

libvpx_test_data = use_extension("@libvpx_test_data//build/bazel/extensions:libvpx_test_data.bzl", "libvpx_test_data")
use_repo(libvpx_test_data, "libvpx_test_vectors")
